### ISSUE TITLE
Difference between this and through?

### ISSUE THREAD

**Issue by dcousens** [wdavidw/node-stream-transform#11]
Hi,

Just in terms of typical usage, what is the difference between this module and [through](https://github.com/dominictarr/through/)?

It would seem both modules serve a similar purpose, albeit this module explicitly inherits from `stream.Transform`.

Just a curious question, no ill intentions :)

**Comment by wdavidw** [comment]
i'm not familiar with through. the idea of this module is to run a transformation function in parallel or sequentially for each written record with a sync or async signature (parallel mode only make sense if async).

**Comment by dcousens** [comment]
For the async variant,  using `through2` in object mode would probably be ideal.

In any case,  no worries, thanks @wdavidw.
