### ISSUE TITLE
Return multiple objects from the transform stream 

### ISSUE THREAD

**Issue by nazarhussain** [wdavidw/node-stream-transform#18]
Is it possible to return multiple objects from the stream pipe, and later stringifier consider those as multiple records to be added to csv. 

```js
stringifier = csv.stringify({ header: true, columns: {a: 'a', b: 'b'} });

csv.transform([{a: 1, b: 2}, {a: 3, b: 4}], function(record){
	return [record, record];
  })
  .pipe(stringifier)
  .pipe(process.stdout);
```

It generates
```
a,b
"{""a"":1,""b"":2}","{""a"":1,""b"":2}"
"{""a"":3,""b"":4}","{""a"":3,""b"":4}"
```

I want the output like this
```
a,b
1,2
1,2
3,4
3,4
```

**Comment by wdavidw** [comment]
You can but using the async api. Simply call the callback multiple times.

**Comment by nazarhussain** [comment]
@wdavidw That works. You are awesome.

**Comment by MichielDeMey** [comment]
Is it possible to do something similar with the streaming API as well?
When using large CSVs they will often not fit in memory. 🙂

**Comment by fnogatz** [comment]
> Is it possible to do something similar with the streaming API as well?
> When using large CSVs they will often not fit in memory.

For anyone coming back to this from Google: Just use the normal `stream.Transform` API, which allows to call `this.emit()` several times:

```js
const transformer = stream.Transform({ objectMode: true })
transformer._transform = function transform(data, encoding, done) {
  this.push(data)
  this.push(data)
  done()
}
```
