### ISSUE TITLE
Not handling entire stream in absence of callback.

### ISSUE THREAD

**Issue by sebakerckhof** [wdavidw/node-stream-transform#19]
Hi,

I'm experimenting with the csv and stream-transform packages.
Here's a little sample repo: https://github.com/sebakerckhof/csvparse/

If I remove the callback on this line:
https://github.com/sebakerckhof/csvparse/blob/master/index.js#L13
Then not the entire stream gets processed (I only see the first 16 lines of the csv being logged).

Is this a bug or am I doing something wrong?

**Comment by wdavidw** [comment]
it's normal, there is nothing triggering the event consumption (look at the stream api). you could add the `consume: true` option or pipe to a consumer (eg `fs.createWriteSteam`)
