### ISSUE TITLE
parallel can use only 4 cores...?

### ISSUE THREAD

**Issue by FreeWillaert** [wdavidw/node-stream-transform#20]
I'm using the Transformer to hash passwords in a CSV file, using [bcrypt](https://www.npmjs.com/package/bcrypt), with the Stream API: piping input stream => transformer => stringifier => output stream.

On my development virtual machine with 4 cores assigned, just setting parallel: 100 was enough to use all cores.

Now I'm testing on a machine with 36 cores (EC2 c4.8xlarge), but no matter what I try, only 4 cores are used...

Is there something obvious I'm missing? With the single-threaded nature of node in mind, is this scenario supposed to work?

**Comment by wdavidw** [comment]
This isnt supposed to work, as you guessed, Node.js is single threaded (even if it will use a few other cores for management), you'll have to spawn processes or use the cluster api. u'll enter the world of distributed computing.

**Comment by FreeWillaert** [comment]
Thanks for responding! Meanwhile I think that using the c++ library allowed for 'some' parallism, but not a lot. But again that's just a guess.
Meanwhile I've entered the world of .Net Core instead - BlockingCollection + Parallel.ForEach = pure beauty :)
