### ISSUE TITLE
Asynchronous transform skips lines?

### ISSUE THREAD

**Issue by vorg** [wdavidw/node-stream-transform#4]
Hi,

I'm trying to parse 22MB csv file with 240k lines. When i use the following async code with callback I get only 16390 records parsed compared to version with no callback and no setTimeout where I get 234841 records.

```javascript
var s = fs.createReadStream('data/all_grants.csv')
.pipe(csv.parse({columns:true}))
.pipe(csv.transform(function(record, callback){
  grants.push(record);
  console.log(grants.length, record.id, record.fundingorganization_name, record.recipientorganization_name, record.awarddate_startdate);
  if (grants.length == 1) {
    console.log(record);
  }
  setTimeout(function() {
    callback(null, record);
  }, 100)
}, { parallel: 1 }))
```

Is this something to do with back-pressure and data coming while transform is waiting for callback?

**Comment by wdavidw** [comment]
have a look at the new "consume" option, closing this issue for now.

**Comment by aheissenberger** [comment]
I could not solve it with `{parallel: 100, consume: true}` but what helped was using https://www.npmjs.com/package/dev-null:
```
var transform = require('stream-transform');
var devnull = require('dev-null');
....
.pipe(transformer).pipe(devnull())
```

**Comment by wdavidw** [comment]
strange, consume is expected to behave similarly.
