### ISSUE TITLE
Parallel option limits?

### ISSUE THREAD

**Issue by devinus** [wdavidw/node-stream-transform#8]
I'm attempting to use `{ parallel: 5 }`, but that makes my pipeline only consume 5 lines rather than consumer 5 at a time. Is there something I'm missing?

**Comment by devinus** [comment]
I believe this is because I'm returning an error in the transform, i.e. `callback(new Error())`. Should this stop the streaming?

**Comment by devinus** [comment]
Also, if I use `callback(null, true);` it will only read 20 lines.

**Comment by wdavidw** [comment]
yes, return a error will stop calling new callbacks

**Comment by wdavidw** [comment]
... this might be wrong, some people have reported bugs that i couldnt reproduce. send me sample a sample reproducing the pb and i will look at it.

**Comment by wdavidw** [comment]
You were probably not consuming the stream. See the new "consume" option if you still have issue and open a new issue with a sample or test case reproducing your issue. closing for now.
